#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'trunk',
 'build_date': '2011-08-08 01:05:06 +0100',
 'clean': None,
 'date': '2011-08-08 01:01:50 +0100',
 'revision_id': 'richard@largo-20110808000150-fc7wea24k7ky5x8l',
 'revno': 74}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
